Shroomiken projectile speed integration #2
Team-Pink/MushroomTowerGame pull request #140
Opened 2023-10-31 23:16 UTC by HellblazePhoenix

Be warned the projectile speed on the Shroomiken is set to a small num meaning the Shroomiken tower won't be very effective until it has been balanced.

2023-10-31 23:34 UTC, XxdalendxX requested changes
Please don't use EditorApplication.Exit(0) in the OpenPauseUI script, This actually makes the editor close instead of exiting out of play mode. "isPlaying == false" makes it so it exits out of play mode.

2023-10-31 23:43 UTC, XxdalendxX commented
Outside of that one problem and intelisense adding "using System.linq" in the attack object, it looks fine. also additionally can you write "UnityEditor.EditorApplication..." that way "using UnityEditor" doesn't get automatically added to the top of the file cause that makes the file mess up when building.

2023-11-12 23:02 UTC, Laochra approved these changes

2023-11-12 23:06 UTC, XxdalendxX approved these changes

2023-11-12 23:10 UTC, merged